/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import DAO.UsuarioMySqlDAO;
import Enums.EnumOperacao;
import Enums.EnumTipoAcesso;
import business.Usuario;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import servicos.ServicoDeMensagens;
import servicos.Validacoes;

/**
 *
 * @author Alipio
 */
public class GerenciarUsuario extends javax.swing.JDialog {

    //Classe para eventos do mouse
    private class ManipuladorMouse implements MouseListener {

        @Override
        public void mousePressed(MouseEvent e) {
            tfNome.setText("");
            tfSenha.setText("");
        }

        @Override
        public void mouseEntered(MouseEvent e) {

        }

        @Override
        public void mouseExited(MouseEvent e) {
        }

        @Override
        public void mouseClicked(MouseEvent e) {
        }

        @Override
        public void mouseReleased(MouseEvent e) {

        }
    }

    private void apagarTextBox() {
        tfNome.setText("");
        tfSenha.setText("");
    }

    /**
     * Creates new form GerenciarUsuario
     */
    public GerenciarUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jLabelStatus.setText("");
        UsuarioMySqlDAO uDao = new UsuarioMySqlDAO();
        try {
            spId.setValue(uDao.proximoId());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Id não encontrado");
        }

        rbCadastrar.setSelected(true);
        spId.setEnabled(false);

        eventoSpIdClicaNaSeta();

        tfNome.setEnabled(true);
        tfSenha.setEnabled(true);      
        
        cbAcesso.setEnabled(true);
        btOperacao.setText("Cadastrar");
        btOperacao.setForeground(Color.BLACK);
        btOperacao.setBackground(Color.GREEN);
    }

    /**
     * Esse evento faz com que a cada click na seta que muda o campo id os
     * demais campos sejam preenchidos, se o id já estiver cadastrado
     */
    private void eventoSpIdClicaNaSeta() {
        spId.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {

                UsuarioMySqlDAO uDao = new UsuarioMySqlDAO();
                Usuario usuario = new Usuario();
                try {
                    int teste = (int) spId.getValue();
                    usuario = uDao.consultaPorId(teste);
                    if (usuario != null) {
                        tfNome.setText(usuario.getNome());
                        tfSenha.setText(usuario.getSenha());
                        cbAcesso.setSelectedItem(usuario.getTipoAcesso().getDescricao());
                    } else {
                        tfNome.setText("");
                        tfSenha.setText("");
                    }

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Id não encontrado");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbCadastrar = new javax.swing.JRadioButton();
        rbAlterar = new javax.swing.JRadioButton();
        rbExcluir = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfSenha = new javax.swing.JTextField();
        cbAcesso = new javax.swing.JComboBox<>();
        spId = new javax.swing.JSpinner();
        btOperacao = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Usuário");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Operação")));

        buttonGroup1.add(rbCadastrar);
        rbCadastrar.setText("Cadastrar");
        rbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCadastrarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbAlterar);
        rbAlterar.setText("Alterar");
        rbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAlterarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbExcluir);
        rbExcluir.setText("Excluir");
        rbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rbCadastrar)
                .addGap(30, 30, 30)
                .addComponent(rbAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(rbExcluir)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbCadastrar)
                .addComponent(rbAlterar)
                .addComponent(rbExcluir))
        );

        jLabel1.setText("ID :");

        jLabel2.setText("NOME:");

        jLabel3.setText("ACESSO:");

        jLabel5.setText("SENHA:");

        tfSenha.setMinimumSize(new java.awt.Dimension(11, 28));

        cbAcesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Padrão", "Administrador" }));

        spId.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btOperacao.setText("jButton1");
        btOperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOperacaoActionPerformed(evt);
            }
        });

        jLabelStatus.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(255, 0, 0));
        jLabelStatus.setText("Id não existe!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(spId, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cbAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelStatus)
                            .addComponent(btOperacao))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3))
                    .addComponent(cbAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btOperacao)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCadastrarActionPerformed
        // TODO add your handling code here:
        //if (jCheckBox1.isSelected()) {
        if (rbCadastrar.isSelected()) {

            spId.setEnabled(false);
            tfNome.setEnabled(true);
            tfSenha.setEnabled(true);
            cbAcesso.setEnabled(true);
            btOperacao.setText("Cadastrar");
            btOperacao.setForeground(Color.BLACK);
            btOperacao.setBackground(Color.GREEN);

            UsuarioMySqlDAO uDao = new UsuarioMySqlDAO();
            int proximoId = 0;
            try {
                proximoId = uDao.proximoId();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Id não encontrado");
            }

            spId.setValue(proximoId);

        }

    }//GEN-LAST:event_rbCadastrarActionPerformed

    private void rbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAlterarActionPerformed
        // TODO add your handling code here:
        if (rbAlterar.isSelected()) {
            eventoSpIdClicaNaSeta();

            spId.setEnabled(true);
            spId.getEditor();

            tfNome.setEnabled(true);
            tfSenha.setEnabled(true);
            cbAcesso.setEnabled(true);

            btOperacao.setText("Alterar");
            btOperacao.setForeground(Color.black);
            btOperacao.setBackground(Color.YELLOW);
        }
    }//GEN-LAST:event_rbAlterarActionPerformed


    private void rbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbExcluirActionPerformed
        // TODO add your handling code here:
        if (rbExcluir.isSelected()) {
            eventoSpIdClicaNaSeta();

            spId.setEnabled(true);
            tfNome.setEnabled(false);
            tfSenha.setEnabled(false);
            cbAcesso.setEnabled(false);
            tfNome.setText("");
            tfSenha.setText("");

            btOperacao.setText("Excluir");
            btOperacao.setForeground(Color.WHITE);
            btOperacao.setBackground(Color.RED);
        }
    }//GEN-LAST:event_rbExcluirActionPerformed

    private void btOperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOperacaoActionPerformed
        UsuarioMySqlDAO uDao = new UsuarioMySqlDAO();
        Usuario usuario = new Usuario();

        try {
            usuario.setId((int) spId.getValue());
            usuario.setNome(tfNome.getText());
            usuario.setSenha(tfSenha.getText());

            EnumTipoAcesso acesso = EnumTipoAcesso.PADRAO;
            if (cbAcesso.getSelectedItem().toString().equals("Administrador")) {
                acesso = EnumTipoAcesso.ADM;
            }
            usuario.setTipoAcesso(acesso);
            
            boolean valido=false;
            if (rbExcluir.isSelected()) {
                valido = Validacoes.validaCamposCadastroUsuario(usuario, EnumOperacao.DELETAR);
                if(valido){
                   uDao.deletarEntidade(usuario.getId(), usuario);                    
                }                 

            } else if (rbCadastrar.isSelected()) {
                valido = Validacoes.validaCamposCadastroUsuario(usuario, EnumOperacao.INSERIR);
                if (valido) {
                    uDao.inserirEntidade(usuario);
                }
            } else if (rbAlterar.isSelected()) {
                valido = Validacoes.validaCamposCadastroUsuario(usuario, EnumOperacao.ALTERAR);
                if (valido) {
                    uDao.alterarEntidade(usuario.getId(), usuario);
                }
            }

            if(valido){
                jLabelStatus.setForeground(Color.GREEN);
               
                jLabelStatus.setText("Usuario Cadastrado");
                
                apagarTextBox();
            }
            else{
                jLabelStatus.setForeground(Color.red);
                jLabelStatus.setText("Dados Incompletos");
                
            }
            
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    ServicoDeMensagens.getMensagem(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btOperacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GerenciarUsuario dialog = new GerenciarUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOperacao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbAcesso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbAlterar;
    private javax.swing.JRadioButton rbCadastrar;
    private javax.swing.JRadioButton rbExcluir;
    private javax.swing.JSpinner spId;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfSenha;
    // End of variables declaration//GEN-END:variables
}

