/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import business.Usuario;
import java.awt.Component;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import servicos.ServicoDeMensagens;
import servicos.Validacoes;
import servicos.GerenciaPasta;
import ColetaDados.PDFMain;
import java.awt.Color;
import static java.lang.Thread.sleep;
import javax.swing.JProgressBar;
import servicos.GerenciaPasta;

/**
 *
 * @author BRUNOSILVA
 */
public class Login extends javax.swing.JFrame {

    private Component frame;

    /**
     * Creates new form TesteLogin
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        painelLogin = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        txtSenha = new javax.swing.JPasswordField();
        btnLogar = new javax.swing.JButton();
        lbLogin = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setPreferredSize(new java.awt.Dimension(392, 260));

        lblNome.setText("Nome:");

        lblSenha.setText("Senha:");

        jProgressBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBar1.setStringPainted(true);

        javax.swing.GroupLayout painelLoginLayout = new javax.swing.GroupLayout(painelLogin);
        painelLogin.setLayout(painelLoginLayout);
        painelLoginLayout.setHorizontalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelLoginLayout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addGap(30, 30, 30)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelLoginLayout.createSequentialGroup()
                                .addComponent(lblSenha)
                                .addGap(26, 26, 26)
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        painelLoginLayout.setVerticalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblSenha))
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
        );

        btnLogar.setText("Entrar");
        btnLogar.setToolTipText("");
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });

        lbLogin.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lbLogin.setText("Seus arquivos estão sendo processados...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btnLogar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(lbLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLogin)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed

        //JOptionPane.showMessageDialog(frame, "Usuário e ou Senha Inválidos!", "Erro", JOptionPane.ERROR_MESSAGE);
        Usuario usuEnvio = new Usuario();
        try {
            GerenciaPasta.PastaDestino();
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

        usuEnvio.setNome(txtUsuario.getText());
        String valor = new String(txtSenha.getPassword());
        String pastaOrigem;
        usuEnvio.setSenha(valor);
        boolean usuarioValido = false;

        try {
            usuarioValido = Validacoes.validaUsuarioSenha(usuEnvio);
            GerenciaPasta.PastaDestino();

            if (usuarioValido) {
                if (GerenciaPasta.isPastaDestino()) {
                    //Se o usuário for válido pega o caminho configurado e carrega os arquivos no banco

//                    btnLogar.setEnabled(false);
//                    pastaOrigem = GerenciaPasta.RetornaCaminhoPasta();
//                    PDFMain.CarregarArquivos(pastaOrigem);
//                    BuscaDeCurriculos amostra = new BuscaDeCurriculos();
//                    dispose();
//                    amostra.setVisible(true);
                                        
                    btnLogar.setEnabled(false);
                    LoadingDados Teste = new LoadingDados();
                    Teste.start();
                    pastaOrigem = GerenciaPasta.RetornaCaminhoPasta();
                    PDFMain.CarregarArquivos(pastaOrigem);
                   

                    BuscaDeCurriculos amostra = new BuscaDeCurriculos();
                    //dispose();
                    amostra.setVisible(false);
                }

            } else {
                JOptionPane.showMessageDialog(frame, ServicoDeMensagens.getMensagem(), "Erro", JOptionPane.ERROR_MESSAGE);

            }

        } catch (IllegalArgumentException | IllegalAccessException ex) {
            JOptionPane.showMessageDialog(frame, ex.getMessage(), "Erro argumento ilegal", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(frame, ex.getMessage(), "Erro na consulta com banco", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnLogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    public class LoadingDados extends Thread {

        public void run() {
            try {
                sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
            int maximo = PDFMain.getLoadMax();
            jProgressBar1.setMaximum(maximo);
         
            for (int i = 0; i < maximo+1 ; i++) {
                try {
                    sleep(100);
                    jProgressBar1.setValue(i);
                    lbLogin.setText("Carregando os arquivos...");
//                    if (jProgressBar1.getValue() <= 2) {
//                        lbLogin.setText("Carregando Sistema ...");
//                    } else if (jProgressBar1.getValue() <= 50) {
//                        lbLogin.setText("Carregando banco de dados ...");
//                    } else if (jProgressBar1.getValue() <= 75) {
//                        lbLogin.setText("Abrindo as tabelas");
//                    } else {
//                        lbLogin.setText("O sistema está sendo iniciado...");
//                    }

                } catch (InterruptedException ex) {
                }
            }

            BuscaDeCurriculos amostra = new BuscaDeCurriculos();
            dispose();
            amostra.setVisible(true);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogar;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
